### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by p4k8**
Am I doing this right? :)

### CODE REVIEW

**Comment by nilmerg** [comment]
Hi!

Nice to see you around here! Yes, you've touched the correct files :+1: 

Though, I wonder why the validation checks didn't run on your pull request :thinking:

**Comment by p4k8** [comment]
Think it's good to go now.

**Comment by nilmerg** [comment]
Good job! Though, you still have massive conflicts. Without these being solved this won't be merged. Have you already taken a look at our [automatic conflict resolution](https://github.com/Icinga/L10n/blob/master/CONTRIBUTING.md#keeping-pull-requests-up-to-date)?

**Comment by p4k8** [comment]
Yeah, but I'm still a bit lost.
Also I don't have write rights to add labels anyway.

**Comment by nilmerg** [comment]
Weeeell, I didn't knew that Github doesn't allow that even for the author of a pull request. What a crap. Added it for you.

**Comment by p4k8** [comment]
So after bot solves conflicts, it is ready to be merged, right?

**Comment by nilmerg** [comment]
Yes, it is! :+1:

I've also changed how the bot can be triggered. Just add a comment containing `/resolve` every time the bot should run and it will do its job.

**Pull request merged**
